added content in __init__.py
bpython/bpython pull request #851
Opened 2020-10-02 11:39 UTC by samsy12

2020-10-02 12:02 UTC, sebastinas commented
But why?

2020-10-07 13:10 UTC, sebastinas requested changes

2020-10-07 13:10 UTC, sebastinas commented on bpython/cli.py
> +        cursor position on the screen and stores it
That's actually correct.

2020-10-11 12:50 UTC, sebastinas commented
I don't think that is useful.

2020-10-11 12:50 UTC, closed without merging

2020-10-11 19:52 UTC, samsy12 commented
Can you please say once more what was the issue with my pr?
And can you please not mark it as invalid/spam? Please, it's kind of
inportant.
No need to merge it, just if you could please remove the invalid/spsm
label, it would be great.

On Sun, Oct 11, 2020, 6:20 PM Sebastian Ramacher <notifications@github.com>
wrote:

> Closed #851 <https://github.com/bpython/bpython/pull/851>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/bpython/bpython/pull/851#event-3863654802>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AONT3WJ4OA6Z4YXBHGY6NHDSKGS25ANCNFSM4SBS5KAA>
> .
>

2020-10-11 20:44 UTC, sebastinas commented
That doesn't change the fact that the spelling fix is wrong and for the other the open question of "why?" is still unanswered.

2020-10-12 07:11 UTC, samsy12 commented
Alright, give me some time, I'll review the code and get back to you.
Meanwhile, can you please remove the invalid label on this pr?
I have some limitations on the amount of data I can consume per day and
with all classes being online, there is only so much other stuff I can do
online. I hope you understand.

On Mon, Oct 12, 2020, 2:14 AM Sebastian Ramacher <notifications@github.com>
wrote:

> That doesn't change the fact that the spelling fix is wrong and for the
> other the open question of "why?" is still unanswered.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/bpython/bpython/pull/851#issuecomment-706765696>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AONT3WNZAARKLP4OKXXHDUDSKIKJ7ANCNFSM4SBS5KAA>
> .
>