Add type annotations to a few files
bpython/bpython pull request #904
Opened 2021-08-07 13:31 UTC by supremestdoggo

This PR just adds some type annotations to a few files. It's not much, but I'm still working on adding type annotations to all files.

2021-08-11 22:15 UTC, sebastinas requested changes
Please also run `black` to ensure consistent formatting after your changes.

2021-08-11 22:15 UTC, sebastinas commented on bpython/args.py
> +def parse(args, extras=None, ignore_stdin=False) -> Tuple:
This could list the types of the tuple's elements.

2021-08-11 22:15 UTC, sebastinas commented on bpython/autocomplete.py
> +    def __init__(self, shown_before_tab: bool=True, mode=AutocompleteModes.SIMPLE) -> None:
mode could be annotated here as well.

2021-08-11 22:15 UTC, sebastinas commented on bpython/autocomplete.py
> +    def matches(self, cursor_offset, line, **kwargs) -> NoReturn:
Is this a good idea for the definition in the base class?

2021-08-13 00:00 UTC, supremestdoggo commented
The commit I just added performs all of the changes you requested, as well as reformatting many files using black.

2021-08-17 07:20 UTC, sebastinas commented
hmm, I had to rerun black again. Merged after doing that.

2021-08-17 07:20 UTC, closed without merging