added type references to pager.py, mypy produced no errors
bpython/bpython pull request #936
Opened 2021-11-01 18:37 UTC by Frostmaine

First time adding to a project on github, started off small. Would really appreciate feedback.

2021-11-02 14:11 UTC, thomasballinger requested changes
Thanks for working on this!

It looks like some builds are failing because `list` can't be subscripted, I added a note about why.

When I run mypy, I get a few errors

```
$ python -m mypy
bpython/pager.py:57: error: Item "None" of "Optional[IO[bytes]]" has no attribute "write"
bpython/pager.py:58: error: Item "None" of "Optional[IO[bytes]]" has no attribute "close"
bpython/_internal.py:7: error: Incompatible types in assignment (expression has type "Callable[[str, bool], None]", variable has type "Callable[[str], None]")
Found 3 errors in 2 files (checked 64 source files)
```

If you figure out how our environments are different let me know and maybe we can add it to some developer docs.

The bpython/_internal.py file is getting more strictly checked now because it uses `page` defined in pager.py. Apparently the real pydoc.pager doesn't take that second argument. I'd be fine with a `type: ignore` for that.

```
pydoc.pager = page  # type: ignore
```

2021-11-02 14:11 UTC, thomasballinger commented on bpython/pager.py
>              popen = subprocess.Popen(command, stdin=subprocess.PIPE)
For me this needs a
```suggestion
            assert popen.stdin is not None
            popen = subprocess.Popen(command, stdin=subprocess.PIPE)
```
to silence mypy errors about stdin maybe being None.

2021-11-02 14:13 UTC, thomasballinger commented
If you aren't able to mypy to produce these errors locally, you can see them in the CI runs on this page.
![image](https://user-images.githubusercontent.com/458879/139864023-5b98af36-a59a-4e3e-bd08-04a7af6a5901.png)

2021-11-09 07:14 UTC, Frostmaine commented
Linter workflow did fail, however it seemed to only be because I modified _internal.py by adding the suggested # type: ignore to pydoc.pager = page.

2021-11-09 08:00 UTC, sebastinas commented
Indeed,  the `black` check failed. So please run `black` on `bpython/_internal.py` and commit the fix.

2021-11-09 16:16 UTC, merged

2021-11-09 16:17 UTC, thomasballinger commented
Thanks for adding these types and fixing these CI issues, this looks good to me. The pypy3 CI failure is failing on main right now too.

2021-11-10 05:16 UTC, Frostmaine commented
Glad to complete my first contribution to a project that I use daily.  I
hope to take the  things I learned about the development process and
continue to contribute in my own small way to this project.  Any feedback
on how I have conducted my interactions with you are welcome.  Thank you so
much for your time.

On Tue, Nov 9, 2021 at 11:17 AM Thomas Ballinger ***@***.***>
wrote:

> Thanks for adding these types and fixing these CI issues, this looks good
> to me. The pypy3 CI failure is failing on main right now too.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/bpython/bpython/pull/936#issuecomment-964306588>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMQSM4JJNZPRYEKCE3TUYZ3ULFCSRANCNFSM5HEVBCTA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>