Added type annotations
bpython/bpython pull request #949
Opened 2022-01-14 20:40 UTC by RCReddyN

I tried adding annotations in the following files, addressing issue #892 :
1. bpython/_internal.py
2. bpython/curtsiesfrontend/interpreter.py

Please, look into it.

2022-01-16 19:01 UTC, thomasballinger commented
@RCReddyN could you fix these conflicts, and then we can run mypy in CI on this.

2022-01-16 19:12 UTC, thomasballinger requested changes

2022-01-16 19:12 UTC, thomasballinger commented on bpdb/__init__.py
> +            print("The program exited via sys.exit(). Exit status: ",)
These formatting changes aren't desired, hopefully running black will fix them? Maybe you have a different autoformatter or different settings?

2022-01-16 19:12 UTC, thomasballinger commented on bpython/_internal.py
> +    def __call__(self, *args: str, **kwargs: int) -> None:
why are kwargs typed as int, is this based on the call signature of a helper? Maybe we should change the signature to match the helper object.

2022-01-16 19:12 UTC, thomasballinger commented on bpython/args.py
> +        "--log-output", "-L", help=_("Log output file"),
this looks like another bad reformat, I won't comment on any others but these formatting-only changes shouldn't be in this PR.

2022-01-16 19:12 UTC, thomasballinger commented on bpython/curtsiesfrontend/interpreter.py
> +from pygments.formatter import Formatter  # type: ignore
If you install the pygments types (see https://github.com/bpython/bpython/blob/main/.github/workflows/lint.yaml#L42) you won't need to ignore these

2022-01-16 19:12 UTC, thomasballinger commented on bpython/curtsiesfrontend/interpreter.py
> +    def __init__(self, color_scheme: Dict, **options: int) -> None:
Dict isn't as helpful as `Dict[whatever, whatever]`

2022-01-16 19:12 UTC, thomasballinger commented on bpython/curtsiesfrontend/interpreter.py
> +    def __init__(self, color_scheme: Dict, **options: int) -> None:
Any why int here?

2022-01-16 19:12 UTC, thomasballinger commented on bpython/curtsiesfrontend/interpreter.py
> +    def format(self, tokensource: Any, outfile: Any) -> None:
This kind of annotation isn't very useful, if you're not sure how to find out (feel free to ask!) then this might a good file to skip

2022-02-02 13:43 UTC, sebastinas requested changes

2022-02-02 13:43 UTC, sebastinas commented on bpython/curtsiesfrontend/interpreter.py
> +        self, locals: Dict[str, Any] = None, encoding: str = None
This should actually be marked with `Optional`.

2022-02-02 13:43 UTC, sebastinas commented on bpython/curtsiesfrontend/interpreter.py
> +    def writetb(self, lines: List[str]) -> None:
This could be `Iterable[str]`.

2022-02-02 13:45 UTC, sebastinas commented on bpython/curtsiesfrontend/interpreter.py
> +        self, locals: Dict[str, Any] = None, encoding: str = None
… ah, but this is just noise from reformatting. This change will need to be rebased.

2022-04-25 21:33 UTC, sebastinas commented
@RCReddyN What's the status of this PR?

2022-05-11 10:18 UTC, closed without merging